name: dbs-dbwk-project

services:
  implementation:
    build:
      context: ./
      args:
        - JAVA_VERSION=${JAVA_VERSION:-21}
    container_name: dbs-dbwk-project-implementation
    env_file: .env
    expose:
      - "${PROJECT_IMPLEMENTATION_URL_PORT:-8080}"
    image: dbs-dbwk-project-implementation:latest
    ports:
      - "${PROJECT_IMPLEMENTATION_URL_PORT:-8080}:${PROJECT_IMPLEMENTATION_URL_PORT:-8080}"
    volumes:
      - ./data:/app/data
  specification:
    container_name: dbs-dbwk-project-specification
    image: swaggerapi/swagger-ui:latest
    environment:
      - PORT=${PROJECT_SPECIFICATION_URL_PORT:-8090}
      - URL=openapi.yaml
      - LAYOUT=BaseLayout
    expose:
      - "${PROJECT_SPECIFICATION_URL_PORT:-8090}"
    ports:
      - "${PROJECT_SPECIFICATION_URL_PORT:-8090}:${PROJECT_SPECIFICATION_URL_PORT:-8090}"
    volumes:
      - ./build/specification/openapi.yaml:/usr/share/nginx/html/openapi.yaml

networks:
  default:
    name: dbs-dbwk-project
